version: '3.5'
services:
    app:
        image: php:7.4-cli
        command: 'php -S 0.0.0.0:8000 -t public'
        container_name: app
        volumes:
            - .:/app
        working_dir: /app
        ports:
            - "8000:8000"
